### ISSUE TITLE
키워드나 감정 분석 요청 시 발생하는 오류

### ISSUE THREAD

**Issue by sky-innerpeace** [DS-DreamIT/ai-api-server#1]
**오류 발생 조건 :** 키워드 추출 요청을 보낼 때 문장에서 키워드를 뽑아낼 수 없으면(문장 길이가 짧거나, '나는 배고파' 등의 문장) 백엔드 서버가 아예 다운됩니다.

요청 결과 코드가 200일때만 키워드를 지정하더라도 그냥 키워드 추출을 실패한 코드를 백엔드에서 받으면 퍼져버리기 때문에, 키워드 추출에 실패하면 statusCode를 200이 아닌 다른 걸로 설정해서 보내주시면 감사하겠습니다~!

**Comment by Soobin-329** [comment]
아예 오류가 발생하면 예외 처리해서 result와 keywords에 빈 배열([])을 return 하도록 하는건 어떨까요? 
원래 배열을 return 해서요!

        try:
            content = request.json.get('content')
            keywords = keyword_extract(content)
            return jsonify({"keywords": keywords})
        except:
            return jsonify({"keywords": []})

**Comment by sky-innerpeace** [comment]
좋습니다!

**Comment by Soobin-329** [comment]
수정해서 올렸습니다~
